services:
  school-money-db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - school-money-data:/var/lib/postgresql/data
    restart: unless-stopped

  school-money-app:
    image: school-money-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8090:8090"
    depends_on:
      - school-money-db
    restart: unless-stopped

volumes:
  school-money-data:
