spring:
  application:
    name: school-money

  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

  datasource:
    url: ${DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

server:
  port: ${SERVER_PORT:8090}

stripe:
  apiKey: ${STRIPE_API_KEY}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET}

app:
  super-admin:
    email: ${SUPER_ADMIN_EMAIL}
    password: ${SUPER_ADMIN_PASSWORD}

  server:
    public-address: ${SERVER_PUBLIC_ADDRESS:http://localhost:8090}

  domain: ${EMAIL_DOMAIN:}

  verification:
    token:
      expiry-hours: ${VERIFICATION_TOKEN_EXPIRY_HOURS:24}
      token-length: ${VERIFICATION_TOKEN_LENGTH:36}

  reset-password:
    token:
      expiry-hours: ${RESET_PASSWORD_TOKEN_EXPIRY_HOURS:1}
      token-length: ${RESET_PASSWORD_TOKEN_LENGTH:36}

  payment:
    success-path: "/api/v1/payments/status/success"
    failed-path: "/api/v1/payments/status/failed"

logging:
  file:
    name: logs/school-money.log
  level:
    root: INFO
    com.example.schoolmoney: DEBUG

minio:
  url: ${MINIO_URL:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}